type Address @entity {
  street: String! @column
  city: String! @column
}

type Person @entity {
  name: String! @column
  phone: String @column
  address: Address! @column
  id: ID! @id
}

type Query {
  personCount: Int!
  allPersons: [Person!]!
  findPerson(name: String!): Person
}

type Mutation {
  addPerson(
    name: String!
    phone: String
    street: String!
    city: String!
  ): Person
}
